version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./data:/app/data
      - ./html_files:/app/html_files
      - ./uploads:/app/uploads
    environment:
      - HTML_DIR=/app/html_files
      - UPLOAD_DIR=/app/uploads
    expose:
      - "40000"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./data:/app/data
      - ./html_files:/app/html_files
      - ./uploads:/app/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 