version: '3.8'
services:
  backend:
    image: qianye60/htmlproxy-backend:latest
    volumes:
      - ./data:/app/data
      - ./html_files:/app/html_files
      - ./uploads:/app/uploads
    environment:
      - HTML_DIR=/app/html_files
      - UPLOAD_DIR=/app/uploads
    ports:
      - "40000:40000"
    networks:
      - app-network

  frontend:
    image: qianye60/htmlproxy-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 