name: 自动构建Docker镜像

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 生成镜像标签
        id: tags
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          COMMIT_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          echo "backend_tags=qianye60/htmlproxy-backend:latest,qianye60/htmlproxy-backend:$TIMESTAMP,qianye60/htmlproxy-backend:$COMMIT_SHA_SHORT" >> $GITHUB_OUTPUT
          echo "frontend_tags=qianye60/htmlproxy-frontend:latest,qianye60/htmlproxy-frontend:$TIMESTAMP,qianye60/htmlproxy-frontend:$COMMIT_SHA_SHORT" >> $GITHUB_OUTPUT

      - name: 构建并推送后端Docker镜像
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.backend_tags }}
          platforms: linux/amd64
          cache-from: type=registry,ref=qianye60/htmlproxy-backend:buildcache
          cache-to: type=registry,ref=qianye60/htmlproxy-backend:buildcache,mode=max,ignore-error=true

      - name: 构建并推送前端Docker镜像
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.frontend_tags }}
          platforms: linux/amd64
          cache-from: type=registry,ref=qianye60/htmlproxy-frontend:buildcache
          cache-to: type=registry,ref=qianye60/htmlproxy-frontend:buildcache,mode=max,ignore-error=true 